language: cpp
env:
  global:
  - DEPS_DIR=${HOME}/deps
  - BRANCH=1.10-dev
before_install:
- git clone https://github.com/alliedmodders/ambuild ${DEPS_DIR}/ambuild
jobs:
  include:
  - name: Linux
    dist: xenial
    python: 3
    before_script:
    - sudo apt-get install -y gcc-multilib g++-multilib binutils p7zip-full
    - |
      pushd ${DEPS_DIR}/ambuild
      sudo python3 setup.py install
      popd
    - chmod +x build.sh
    script:
    - "./build.sh"
  - name: Windows
    os: windows
    python: 3.8
    env:
    - PATH=/c/Python38:/c/Python38/Scripts:${PATH}
    before_script:
    - choco install -y visualstudio2019buildtools python3 --package-parameters "--add
      Microsoft.VisualStudio.Component.VC.Tools.x86.x64";
    - |
      pushd ${DEPS_DIR}/ambuild
      python setup.py install
      popd
    script:
    - "./build.bat"
before_deploy:
- git config --local user.name "PerfectLaugh"
- git config --local user.email "denniswu81229@gmail.com"
- export TRAVIS_TAG=deploy-$TRAVIS_BUILD_NUMBER
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Dx7/OMs24q00Fqry/Djg+winO6PvuI1iWVCYQ6BH7/Tj8jhrnPvGQMzPBFphg63X/wp7/Cci5VWAGCcSrMHKDv+pTlxKWcnBFCQCFQnizFqgnkBY4uNq34hmt2Libg99ConjES1xGP+ELe6+GJKrfit0ffHyhLGansMrSMYsDRDzlbmeVIs4S8QYrHyr1R0mgmGcdYzLy+eJW1K4EfIIrS38eNb+GyAUe8ybQOm1u1lROg6SqVYwG7mbGTQDVS47otVVg0WFJ/asbiC7tJZvPTMI4/A/2UDWzHgNho0b7sp43wJv9uowgRdA+6cUdlqKiSS8lY9dc4U+vTgPbjVKClPa3Pk86p07IZ7lldXgwX8DHkkxLGwW28U6mBW7zzlMHMQRFuv5GxvKEg4we2qexL54f4LOfQFontpDkTbR+6ecrZyLliElNQUVA6S7PJHXtcjtXRY+aCLlUb3DNHTKkhgogJHVE5n4GjfESgUU/mN0pd3OOkOd6s3RC7YGOzy1i0aUj+DhWONcbitVD6HzZtvnMEnc0VyjV3VZyUkabr7MmCAr2XTfAZjgTBbmtYR1v8T6E7PoIQm6k5mHHCrWa/EU28jLLIyWgRKGsI4hpmV58tue90L7rFLNCy1EFTLTN+4hoHGs8ZiZqkLxG9CuKBR54seZ21tbfBi0vs2HRM8=
  file:
  - build/package/addons/sourcemod/extensions/socket.ext.dll
  - build/package/addons/sourcemod/extensions/socket.ext.so
  on:
    repo: PerfectLaugh/sm-ext-socket
  skip_cleanup: 'true'
