language: cpp
env:
  global:
  - DEPS_DIR=${HOME}/deps
  - BRANCH=1.10-dev
before_install:
- git clone https://github.com/alliedmodders/ambuild ${DEPS_DIR}/ambuild
jobs:
  include:
  - name: Linux
    dist: xenial
    python: 3
    before_script:
    - sudo apt-get install -y gcc-multilib g++-multilib binutils p7zip-full
    - |
      pushd ${DEPS_DIR}/ambuild
      sudo python3 setup.py install
      popd
    - chmod +x build.sh
    script:
    - "./build.sh"
  - name: Windows
    os: windows
    python: 3.8
    env:
    - PATH=/c/Python38:/c/Python38/Scripts:${PATH}
    before_script:
    - choco install -y visualstudio2019buildtools python3 --package-parameters "--add
      Microsoft.VisualStudio.Component.VC.Tools.x86.x64";
    - |
      pushd ${DEPS_DIR}/ambuild
      python setup.py install
      popd
    script:
    - "./build.bat"
before_deploy:
- git config --local user.name "PerfectLaugh"
- git config --local user.email "denniswu81229@gmail.com"
- export TRAVIS_TAG=deploy-$TRAVIS_BUILD_NUMBER
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Tr+edtc3Y+H/2CurQwRu1M9Aw8TH2RWNdjmdg2uZ3nQz1TqEi1mMIAwZGp4FTcfNP2+utTHijmpcovONVIYObOs+pL+/TkwKCkLmdzGHpxCC1DlgrHTGT7YhGuaf8gL4PwvFtTHzG8DaZCshNienf8xZJO1nDcqbtmYnQK6zAbUuEgDZBpc7VHfdxQBZZ0EIzEqhoR4Y6bEpb9l3lsbRc83F6fDf/eNbRhq92ioSpWYgX0y3zqCN8LzStdaqfbZlVmsJBy+aNkDhtYrLQmFE+E61y+Rc3K6jwRdzRCbSIeeVnUD+auj6Lrn1ydeiQF4FMG9cZ9J38EZ/aqwR6kMMeuJFvWHluH925rJnSmOkNJgfDKs+SiIeIwKIMLl8zE/8EySkH4bKpMfvC3A7UEw/0FeS+/5qW6UDMszC5H8W1I01FQ62JCjDuc+vm4jK8fCBWpaTffj4+ttLBP6jyTcVpllRnhnasORdDhRfoD22Fuj0jHAn+dMYs5iqWO3LlcFxcRXVICGXNwh+Y0KU6gfA2xKTUAKGZB7tOCNnTgfGOy7OCFdjSnWPIkro7DRUNifVwwGSUgztVMrgm99iE1IfCySKiYKW0tfwHHGLD3urlSC4J8MoNQLqCJ5sZPhb0472Vwt7oC+Pbfww+AGdrqLpYb3PzuRzuSlHT6T9Jg6TOHs=
  file:
  - build/package/addons/sourcemod/extensions/socket.ext.dll
  - build/package/addons/sourcemod/extensions/socket.ext.so
  on:
    repo: PerfectLaugh/sm-ext-socket
  skip_cleanup: 'true'
